---
# title: "Using Machine Learning and Big Data to Model Car Dependency: an Exploration Using Origin-Destination Data"
title: "Using Machine Learning and Big Data to Model Car Dependency: Progress Report 1 - Input Data"
author: Robin Lovelace and Ilan Fridman-Rojas
date: "`r Sys.Date()`"
bibliography: ../references.bib
output: rmarkdown::pdf_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!-- ## What is car dependency? -->

<!-- Car dependency should be easy to define: a measure of the extent to which people *depend* on their cars. -->
<!-- But what does this actually mean? -->
<!-- Unless your car doubles as a life-support system, it is unlikley that you literally depend on it for survival. -->
<!-- More likely you depend on the car for trips that are *seen as essential*, for modern life. -->
<!-- Whether it's for doing the 'weekly shop', dropping children off at school or taking a sick relative to hospital at an affordable, car use can easily become integral modern life. -->

<!-- Of course, each of these trips could have either been made by a different mode or not made at all and (except potentially in the case of taking a relative to hospital) nobody would die. -->
<!-- Car dependency is thus about observed behaviour than hypothetical consequences of going *cold turkey*. -->
<!-- The analogy of a drug dependency is useful. -->
<!-- Drug dependents will not die if they can no longer indulge their addition. -->
<!-- But life will be hard, at least for a while after, when they stop. -->
<!-- Similarly, those who are car dependent will find it hard to adjust to life after their car has been taken away. -->

<!-- From a policy perspective car dependency is problematic due to its negative consequences, not in its own right.  -->
<!-- Notwithstanding questions of whether government policy encourages car dependency,  -->


<!-- It is important to note that car dependency is not necessarily  -->

<!-- ## Established methods for car dependency research -->

<!-- There is a long history of reasearch into the concepts of car dependency and, more broadly, mode choice.  -->


<!-- [@mogridge_self-defeating_1997] -->


## Introduction

The primary aim of this project is to show the power and potential benefits of machine learning algorithms in analysing transport data and demonstrating previously impossible methods to gain policy-releant insight from evergrowing datasets. The ultimate goal is for these patterns to allow for data-driven policy decisions to be taken. This could lead to improvements compared with decisions based on basic indicators, intuition, and experience alone.

## Definition of car dependency

<!-- Say how we define car dependency, and something about the model used to estimate 'expected level of driving' here please. -->

## Input data

For simplicity and maximum accessibility we focussed on datasets which are open (publicly available). Three main input dataset types have been used in this research:

- Origin-destination (OD) commute data from the 2011 Census data.
- Geographically aggregated socio-demographic data from the 2011 Census.
- Geographic variables associated with each OD pair.

The Census was used as the primary input dataset because it provides so many variables relevant to car dependency. To our knowledge, the breadth of input datasets have never been analysed together in a single project.

The case study region used for this project was **West Yorkshire**. This case study was selected due to the wide range of social and geographical environments linked to car dependency found here: it includes rural, urban, deprived and privaledged areas.

### Origin-destination data

The basic input data used was a table reporting the number of people travelling, by main mode of transport, commuting to work between Middle-Super Output Areas (MSOAs, average population: ~7,500).

To convert the non-geographical OD dataset into geographic data we used the function `od2line()` from the **stplanr** R package.

<!-- Maybe add example code here. -->
<!-- More important: add a figure showing the flows -->

We will hereon refer to each home-work (origin-destination) pair and its corresponding number of commuters, in geographic form, as a *flow*. This table ([available online](http://wicid.ukdataservice.ac.uk/)) contains the code for each origin and destination zone, as well as the number of people which employed each of the following modes of transport: work at home (no transport used), some form of metro, train, bus or coach, taxi, motorcycle or scooter, drive a car or van, passenger in car or van, bicycle, walk, other. We grouped together people who drive or are passengers to estimate the car propensity (fraction).


To this base table there are two ways to further increase the data included for modelling: the Census provides numerous other demographic and economic measures and indicators which can be linked to the commuter's home MSOA ([available here](https://www.nomisweb.co.uk/census/2011/data_finder)), and it also provides workplace data which a group of researchers at the University of Southampton have conveniently created a classification of (by work type, [available online as well](http://cowz.geodata.soton.ac.uk/download/)) which can be linked to the workplace MSOA.

### Socio-demographic data

The geodemographic data relevant to each origin (home) MSOA which was deemed relevant and annexed to the flows data consists of the following variables: number of people in particular age brackets, number of people of each gender, car or van availability (including number of homes with 0,1,2,etc. cars), population density, number of economically active and inactive people, general health (number of people with very good, fair, etc. general health), number of people per ethnicity group, number of people by maximum qualification level, and lastly, average number of rooms, bedrooms and fraction of homes with central heating.

<!-- This table does not work - please update -->

In addition to this we included the workplace zone classification which assigns each destination MSOA (workplace) to one of the following groups:
                         Retail         1
                       Top jobs         2
                  Metro suburbs         3
              Suburban services         4
 Manufacturing and distribution         5
                          Rural         6
            Servants of society         7
            
### Spatial data

In addition to this Census data we gathered and computed spatial data as well. We have obtained the location of motorways through the [OSM API](https://osmdatar.github.io/osmdata/articles/osmdata.html), and the positions of train stations, coach stations, and bus stops from the [NAPTAN dataset](http://naptan.app.dft.gov.uk/datarequest/help). This allowed us to calculate geographical distances between flow lines and motorways, train stations, coach stations, and bus stops. This proximity and accessibility data is arguably vital to best understand and model car usage propensity, and has for the first time become readily available via the OSM platform, and analysis of the type we aim to do next should be cutting-edge data analysis.

## Overview of input data

A complete list of the variable names used in the input dataset for the machine learning algorithms is provided below.

<!-- Please add list of all ~50 variables here. -->

## Next steps

Based on the input data documented in the previous sections, we have already made a start on developing and running code to identify the variables associated with car dependency. We will use the following approaches (in order of complexity and implementation):



## References