# library(dplyr)
# library(sp)
# unzip("data/wyflows_w_response_and_geo.zip", exdir = "data")
# train = readr::read_csv("data/wyflows_w_response_and_geo.csv")
# head(train)
# # View(train)
# names(train)
# m = lm(formula = response ~ workhome + dis data = train)
# summary(m)
